package com.sdzee.daoImplementations;

import static com.sdzee.dao.DAOUtilitarian.initialisationPreparedRequest;
import static com.sdzee.dao.DAOUtilitarian.silentClose;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import com.sdzee.beans.News;
import com.sdzee.dao.DAOException;
import com.sdzee.dao.DAOFactory;
import com.sdzee.daoInterfaces.NewsDAOInterface;

public class NewsDAOImplementation implements NewsDAOInterface {
	
	private DAOFactory daoFactory;
	
	private static final String SQL_LAST_ID = "SELECT id FROM news";
	private static final String SQL_THREE_LAST_ID = "SELECT id FROM news ORDER BY id DESC LIMIT 3";
	private static final String SQL_CREATE_NEWS = "INSERT INTO news (title, image, content, date, summary) VALUES (?,?,?,?,?)";
	private static final String SQL_UPDATE_NEWS = "UPDATE news SET title = ?, content = ?, image = ?, lastEdit = NOW(), summary = ? WHERE id = ?";
	private static final String SQL_GET_NEWS = "SELECT id, title, image, content, DATE_FORMAT(date,'%d/%m/%Y') AS date, DATE_FORMAT(lastEdit,'%d/%m/%Y') AS lastEdit, summary FROM news WHERE id = ?";
	private static final String SQL_DELETE_NEWS = "DELETE FROM news WHERE id = ?";
	
	private static final String ID_FIELD = "id";
	private static final String TITLE_FIELD = "title";
	private static final String CONTENT_FIELD = "content";
	private static final String IMAGE_FIELD = "image";
	private static final String DATE_FIELD = "date";
	private static final String LASTEDIT_FIELD = "lastEdit";
	private static final String SUMMARY_FIELD = "summary";
	
    public NewsDAOImplementation( DAOFactory daoFactory ) {
        this.daoFactory = daoFactory;
    }

	@Override
	public void createNews(News news) throws DAOException {
        Connection connexion = null;
        PreparedStatement preparedStatement = null;
        ResultSet autoGeneratedValues = null;
        
        try {
        	connexion = daoFactory.getConnexion();
        	
        	String title = news.getTitle();
        	String content = news.getContent();
        	String image = news.getImage();
        	String date = news.getDate();
        	String summary = news.getSummary();
        	
            preparedStatement = initialisationPreparedRequest(connexion, SQL_CREATE_NEWS, true, title, image, content, date, summary);
            int statut = preparedStatement.executeUpdate();
            
            if ( statut == 0 ) {
                throw new DAOException( "Échec de la création de l'utilisateur, aucune ligne ajoutée dans la table." );
            }
            
            autoGeneratedValues = preparedStatement.getGeneratedKeys();
            if ( autoGeneratedValues.next() ) {
                news.setId( autoGeneratedValues.getInt( 1 ) );
            } else {
                throw new DAOException( "Échec de la création de l'utilisateur en base, aucun ID auto-généré retourné." );
            }
        } catch (SQLException e){
        	throw new DAOException( e );
        } finally {
            silentClose( autoGeneratedValues, preparedStatement, connexion );
        }
		
	}

	@Override
	public void updateNews(News news) throws DAOException {
        Connection connexion = null;
        PreparedStatement preparedStatement = null;
        
        int id = news.getId();
        String title = news.getTitle();
        String content = news.getContent();
        String image = news.getImage();
        String summary = news.getSummary();
        
        try {
        	connexion = daoFactory.getConnexion();
            preparedStatement = initialisationPreparedRequest( connexion, SQL_UPDATE_NEWS, false, title, content, image, summary, id);
            int statut = preparedStatement.executeUpdate();
            
            if ( statut == 0 ) {
                throw new DAOException( "Échec de la mise à jour de la news, aucune ligne mise à jour dans la table." );
            }
            
        } catch (SQLException e) {
        	throw new DAOException("La table News n'a pas pu être mise à jour.", e);
		} finally {
			silentClose(preparedStatement, connexion);
		}
		
	}

	@Override
	public News getNews(int id) throws DAOException {
        Connection connexion = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        News news = null;

        try {
            connexion = daoFactory.getConnexion();
            preparedStatement = initialisationPreparedRequest( connexion, SQL_GET_NEWS, false, id );
            resultSet = preparedStatement.executeQuery();
            
            if ( resultSet.next() ) {
                news = map( resultSet );
            }
        } catch ( SQLException e ) {
            throw new DAOException( e );
        } finally {
            silentClose( resultSet, preparedStatement, connexion );
        }

        return news;
	}
	
	@Override
	public News[] getThreeLastNews() throws DAOException {
		int[] ids = threeLastIds();
		News[] newsList = new News[3];
		for (int i = 0; i < 3; i++) {
			if (ids[i] != -1) {
				News n = getNews(ids[i]);
				newsList[i] = n;
			}
		}
		
		return newsList;
	}

	@Override
	public ArrayList<News> getAllNews() throws DAOException {
		ArrayList<News> newsList = new ArrayList<News>();
		ArrayList<Integer> allIds = allId();
		
		for (int i : allIds) {
			News t = getNews(i);
			if (t != null) {
				newsList.add(t);
			}
		}
		
		return newsList;
	}
	
	@Override
	public void deleteNews(int id) throws DAOException {
        Connection connexion = null;
        PreparedStatement preparedStatement = null;
        
        try {
			connexion = daoFactory.getConnexion();
			preparedStatement = initialisationPreparedRequest( connexion, SQL_DELETE_NEWS, false, id);
			int statut = preparedStatement.executeUpdate();
			
			if (statut == 0) {
				throw new DAOException( "Problème lors de la suppression de la news." );
			}
		} catch (SQLException e) {
			throw new DAOException( "Problème lors de la suppression de la news." );
		} finally {
			silentClose(preparedStatement, connexion);
		}
		
	}

	@Override
	public boolean exists(int id) throws DAOException {
        Connection connexion = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        
		boolean exists = false;
		
		try {
			connexion = daoFactory.getConnexion();
			preparedStatement = initialisationPreparedRequest(connexion,SQL_LAST_ID, false);
			resultSet = preparedStatement.executeQuery();
			
			while (resultSet.next()) {
				int currentId = resultSet.getInt(ID_FIELD);
				if(currentId == id) {
					exists = true;
				}
			}
			
		} catch (SQLException e) {
			throw new DAOException("La news n'existe pas.", e);
		} finally {
			silentClose(resultSet, preparedStatement, connexion);
		}
		
		return exists;
	}
	
    private static News map( ResultSet resultSet ) throws SQLException {
    	News news = new News();
    	news.setId( resultSet.getInt( ID_FIELD ) );
    	news.setTitle( resultSet.getString( TITLE_FIELD ) );
    	news.setContent( resultSet.getString( CONTENT_FIELD ) );
    	news.setImage( resultSet.getString( IMAGE_FIELD ) );
    	news.setDate( resultSet.getString( DATE_FIELD ) );
    	news.setLastEdit(resultSet.getString( LASTEDIT_FIELD ));
    	news.setSummary(resultSet.getString(SUMMARY_FIELD));
        return news;
    }

	@Override
	public int lastId() throws DAOException {
        Connection connexion = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        
		int id = -1;
		
		try {
			connexion = daoFactory.getConnexion();
			preparedStatement = initialisationPreparedRequest(connexion,SQL_LAST_ID, false);
			resultSet = preparedStatement.executeQuery();
			
			while (resultSet.next()) {
				int currentId = resultSet.getInt(ID_FIELD);
				if(currentId > id) {
					id = currentId;
				}
			}
			
		} catch (SQLException e) {
			throw new DAOException("Problème lors de la récupération du last ID", e);
		} finally {
			silentClose(resultSet, preparedStatement, connexion);
		}
		if (id < 0) {
			id = 0;
		}
		return id;
	}
	
	private int[] threeLastIds() {
        Connection connexion = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        
		int[] ids = {-1,-1,-1};
		
		try {
			connexion = daoFactory.getConnexion();
			preparedStatement = initialisationPreparedRequest(connexion,SQL_THREE_LAST_ID, false);
			resultSet = preparedStatement.executeQuery();
			
			int i = 0;
			
			while (resultSet.next()) {
				int currentId = resultSet.getInt(ID_FIELD);
				if (i < 3) {
					ids[i] = currentId;
				}
				i++;
			}
			
		} catch (SQLException e) {
			throw new DAOException("Problème lors de la récupération du last ID", e);
		} finally {
			silentClose(resultSet, preparedStatement, connexion);
		}
		return ids;
	}
	
	private ArrayList<Integer> allId() {
        Connection connexion = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        
		ArrayList<Integer> ids = new ArrayList<Integer>();
		
		try {
			connexion = daoFactory.getConnexion();
			preparedStatement = initialisationPreparedRequest(connexion,SQL_LAST_ID, false);
			resultSet = preparedStatement.executeQuery();
			
			while (resultSet.next()) {
				int currentId = resultSet.getInt(ID_FIELD);
				if(!ids.contains(currentId)) {
					ids.add(currentId);
				}
			}
			
		} catch (SQLException e) {
			throw new DAOException("Problème lors de la récupération des ID", e);
		} finally {
			silentClose(resultSet, preparedStatement, connexion);
		}
		return ids;
	}
}
